const MusicData = [
    {
        id: 0,
        name: 'Tonight Tonight',
        singer: 'EGOIST',
        path: 'audio/Tonight Tonight.mp3',
        cover: 'images/EGOIST.jpg',
    },
    {
        id: 1,
        name: '僕らまだアンダーグラウンド',
        singer: 'Eve',
        path: 'audio/僕らまだアンダーグラウンド.mp3',
        cover: 'images/Eve.jpg',
    },
    {
        id: 2,
        name: '心予報',
        singer: 'Eve',
        path: 'audio/横竖撇点折.mp3',
        cover: 'images/Eve.jpg',
    },
    {
        id: 3,
        name: '遊生夢死',
        singer: 'Eve',
        path: 'audio/遊生夢死.mp3',
        cover: 'images/Eve.jpg',
    },
    {
        id: 4,
        name: '横竖撇点折',
        singer: '米白',
        path: 'audio/横竖撇点折.mp3',
        cover: 'images/米白.jpg',
    },
    {
        id: 5,
        name: '月光',
        singer: '胡彦斌',
        path: 'audio/月光.mp3',
        cover: 'images/胡彦斌.jpg',
    }, {
        id: 6,
        name: '斜陽',
        singer: 'ヨルシカ',
        path: 'audio/斜陽.mp3',
        cover: 'images/ヨルシカ.jpg',
    },
    {
        id: 7,
        name: 'Lemon',
        singer: '米津玄师',
        path: 'audio/Lemon.mp3',
        cover: 'images/米津玄师.png',
    },
    {
        id: 8,
        name: `It'S All About You`,
        singer: 'EGOIST',
        path: `audio/It'S All About You.mp3`,
        cover: 'images/EGOIST.jpg',
    },
]